name: Auto Approval
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v2.0.0
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
